### ISSUE TITLE
How to access admin panel after installing the skeleton on ftp

### ISSUE THREAD

**Issue by lucieduverger** [tranduyhung/grav-skeleton-appi#1]
Hi, sorry but could you please mention what is the relative url to access the admin panel when you install a new Grav site from your skeleton.
Tx

**Comment by tranduyhung** [comment]
The skeleton doesn't include Admin plugin, you need to install it by yourself if you need it.

**Comment by lucieduverger** [comment]
I cannot find how to get a special package to add the admin plugin and where to place it on my ftp. I do not have access to my server console. Morever, I'm not a developper :( so I need to stick to upload files on my ftp and use the web browser to set my website.

**Comment by tranduyhung** [comment]
You can install any plugins and themes via FTP, here is the instruction for how install Admin plugin and its dependencies: https://github.com/getgrav/grav-plugin-admin#manual-installation
